Fixed FAQ accordion dropdown
HackNC/fall2023 pull request #12
Opened 2023-07-15 14:02 UTC by aryasalian

This resolves task #6 from the Projects tab. The 2022 website omitted the functionality of extracting text from the .JSON file and the 2021 website didn't have the dropdown functionality. I've merged both of these into one and switched the long Javascript code for the dropdown functionality written in the 2022 website with a shorter jQuery code instead.

2023-07-17 07:21 UTC, atoneyd requested changes
This is great, thank you for commenting the code and giving context for the changes you made. Left some comments to clean up the code and requesting some small styling changes:

Could you make each question centered with the icon horizontally, and make it not wrap around the icon on a new line? See the FAQ section from https://fall2020.hacknc.com/ for an example of how it should look. I think we should reduce the spacing between each question as well.

2023-07-17 07:21 UTC, atoneyd commented on static/js/main.js
> +        //console.log("clicked!");
remove the console.log

2023-07-17 07:21 UTC, atoneyd commented on index.html
>                      <!-- <button class="involve-button hide-on-med-and-down"><a href="https://forms.gle/cqkwFZum1BihNbpKA">2022 Hacker Interest form</a></button> -->
Can you actually remove this commented-out code from the previous PR? We don't need it for now and can always reference previous commits if we want to add it back in eventually

2023-07-17 14:56 UTC, aryasalian commented
> This is great, thank you for commenting the code and giving context for the changes you made. Left some comments to clean up the code and requesting some small styling changes:
> 
> Could you make each question centered with the icon horizontally, and make it not wrap around the icon on a new line? See the FAQ section from https://fall2020.hacknc.com/ for an example of how it should look. I think we should reduce the spacing between each question as well.

Sorted that out, how about now?

2023-07-18 04:20 UTC, atoneyd approved these changes
LGTM!

2023-07-18 08:53 UTC, aryasalian commented
Great! Merging it.

2023-07-18 08:53 UTC, merged