improved sponsor section organization
HackNC/fall2023 pull request #16
Opened 2023-07-18 11:17 UTC by aryasalian

This resolves task #10  from the Projects tab. I didn't change the sponsor logo images because I wasn't sure exactly where those images should be stored in the repo but I think we should look into the images for Infosys, Deutsche Bank and Kappa Theta Pi: they have a white background. We should have a transparent image for those logos too like the others.

2023-07-19 05:38 UTC, atoneyd requested changes
Looks great! But could you add some styling for mobile using @media in the CSS? the icons look really small and spaced out when you are on your phone. I think they should be a bit bigger/ less spacing between them, and wrapping may help it look better. Whatever you think looks good!

2023-07-19 05:38 UTC, atoneyd commented on index.html
> +                <!--shifted this up here, similar to pearlhacks and the 2022 hacknc website-->
You can remove this comment; any context/reasoning like this can just go in the pull request description.

2023-07-19 05:40 UTC, atoneyd commented
> We should have a transparent image for those logos too like the others.

True, our sponsors for this year haven't been finalized yet, but once they are there'll be another task to replace the images

2023-07-19 12:46 UTC, aryasalian commented
> Looks great! But could you add some styling for mobile using @media in the CSS? the icons look really small and spaced out when you are on your phone. I think they should be a bit bigger/ less spacing between them, and wrapping may help it look better. Whatever you think looks good!

Check it now. I've used a flexbox to make it responsive instead of applying @media rules, I hope that's not an issue since we only care about the image resizing. I've removed the viewport dependent dimension styling for all images, they won't shrink with a decrease in viewport size anymore. Instead they'll wrap to the next row. LMK what you think!

2023-07-19 12:47 UTC, aryasalian commented
> > We should have a transparent image for those logos too like the others.
> 
> True, our sponsors for this year haven't been finalized yet, but once they are there'll be another task to replace the images

Alright!

2023-07-21 06:49 UTC, atoneyd approved these changes
Thank you, it looks good! I think you forgot to remove the comment on line 207; once you've done that you can merge in this branch

2023-07-21 08:49 UTC, aryasalian commented
yepp, all done! thanks!

2023-07-21 08:49 UTC, merged